### ISSUE TITLE
install error on windows using proxy

### ISSUE THREAD

**Issue by feifeizhuge** [guillemr/robust-fpop#1]
when I try to install this package in Rstudio(1.1.463) on window7 computer, it occur two big problems.

1. `Error in curl::curl_fetch_memory(url, handle = h) : Could not resolve host: api.github.com`

2. `BinSeg_MultiDim.h:21:26: fatal error: gsl/gsl_math.h: No such file or directory`

After one day struggle I have solved all problems.  

#  1.  solving the first one (proxy)

About question one this is because you use company's computer and all access to Internet is through proxy. So your access to github is blocked and need use `install_local('path')` to install this package locally.  

- [ ] download the github file as zip form 

- [ ] use `install_local('path')` . Here path is the path where you put your zip file 

- [ ] at the same time you are highly probable required to install Rtools, just do it 

#  2. the second one (missing  gsl/gsl_math.h )
you miss a gsl library. This is the GNU Scientific Library. To solve this you need to download Gsl for Windows, here is the link [gsl library](https://sourceforge.net/projects/gnuwin32/)  

- [ ] install this gsl on your computer 

- [ ] find `C:\Users\yourname\GnuWin32\include\gsl ` and copy the whole file of gsl and put it to your R path `C:\Users\yourname\Documents\R\R-3.5.3\include` 

- [ ] Fertig! :+1:

**Comment by guillemr** [comment]
Thanks!

________________________________
De : feifeizhuge <notifications@github.com>
Envoyé : mercredi 13 mars 2019 09:51
À : guillemr/robust-fpop
Cc : Subscribed
Objet : [guillemr/robust-fpop] install error on windows using proxy (#1)


when I try to install this package in Rstudio(1.1.463) on window7 computer, it occur two big problems.

  1.  Error in curl::curl_fetch_memory(url, handle = h) : Could not resolve host: api.github.com

  2.  BinSeg_MultiDim.h:21:26: fatal error: gsl/gsl_math.h: No such file or directory

After one day struggle I have solved all problems.

1. solving the first one (proxy)

About question one this is because you use company's computer and all access to Internet is through proxy. So your access to github is blocked and need use install_local('path') to install this package locally.

  *    download the github file as zip form

  *    use install_local('path') . Here path is the path where you put your zip file

  *    at the same time you are highly probable required to install Rtools, just do it

2. the second one (missing gsl/gsl_math.h )

you miss a gsl library. This is the GNU Scientific Library. To solve this you need to download Gsl for Windows, here is the link gsl library<https://sourceforge.net/projects/gnuwin32/>

  *    install this gsl on your computer

  *    find C:\Users\yourname\GnuWin32\include\gsl and copy the whole file of gsl and put it to your R path C:\Users\yourname\Documents\R\R-3.5.3\include

  *    Fertig! ??

-
